# Default values for cube-query.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  image:
    repository: "satapps/cubequery-server"
    tag: "953e900"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  service:
    type: LoadBalancer
    port: 5000
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: cubequery.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources: {}
  env: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

worker:
  image:
    repository: "satapps/cubequery-worker"
    tag: "b750553"
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  replicaCount: 1
  resources: {}
  env: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

redisServiceHost: "redis-master"

aws:
  accessKeyId: "AKIAIOSFODNN7INVALID"
  secretAccessKey: "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"
