apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  namespace: dask
spec:
  selector:
    app: dask
    component: scheduler
  ports:
    - name: scheduler
      port: 8786
      targetPort: 8786
    - name: bokeh
      port: 8787
      targetPort: 8787
